# Generated by Django 4.2.7 on 2026-02-03 10:16

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_phone', models.CharField(max_length=50)),
                ('customer_address', models.CharField(max_length=255)),
                ('customer_comment', models.TextField(blank=True)),
                ('subtotal_uzs', models.PositiveIntegerField()),
                ('locale', models.CharField(choices=[('ru', 'RU'), ('uz', 'UZ')], max_length=2)),
                ('theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark')], max_length=5)),
                ('status', models.CharField(choices=[('new', 'New'), ('sent', 'Sent'), ('failed', 'Failed')], default='new', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('price_uzs', models.PositiveIntegerField()),
                ('currency', models.CharField(default='UZS', max_length=3)),
                ('sizes', models.JSONField()),
                ('in_stock', models.BooleanField(default=True)),
                ('image_urls', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title_snapshot', models.CharField(max_length=255)),
                ('description_snapshot', models.TextField()),
                ('price_snapshot_uzs', models.PositiveIntegerField()),
                ('image_url_snapshot', models.URLField()),
                ('qty', models.PositiveIntegerField()),
                ('selected_size', models.PositiveIntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.product')),
            ],
        ),
    ]
