# Generated by Django 4.2.7 on 2026-02-03 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_telegram_username',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
