# Generated by Antigravity to remove sample product

from django.db import migrations

def remove_sample_product(apps, schema_editor):
    Product = apps.get_model('shop', 'Product')
    Product.objects.filter(slug='serebryanoe-kolco').delete()

class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_fix_encoding'),
    ]

    operations = [
        migrations.RunPython(remove_sample_product),
    ]
